project_id = "iqmskopbhrzqqqjewdzv"

[functions.sync-artist-images]
verify_jwt = false

[functions.bulk-sync-artist-images]
verify_jwt = false

[functions.download-artist-images]
verify_jwt = false

[functions.auto-generate-profile]
verify_jwt = true