
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyicnvkbwjsssmrfcfqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5aWNudmtid2pzc3NtcmZjZnFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxNDU3NTIsImV4cCI6MjA1NDcyMTc1Mn0.KxX-LLai3rTdrS8idf6NLCedH3JSFw6nAXsBeAHq18Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
