// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqmskopbhrzqqqjewdzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxbXNrb3BiaHJ6cXFxamV3ZHp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0MDA3MTksImV4cCI6MjA1NDk3NjcxOX0.lIp4QNNn61csUT7kYxtT8BQkEkfCLCJIlXS-KGCgIhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});